Repository 247CloudLibrary/client-users, pull requests merged in 2022-04, with the labels that each got.

#14 [Auth] 회원가입 페이지 추가
  .gitignore
  build/asset-manifest.json
  build/favicon.ico
  build/index.html
  build/logo192.png
  build/logo512.png
  build/manifest.json
  build/robots.txt
  build/static/js/main.14f3b4f0.js
  build/static/js/main.14f3b4f0.js.LICENSE.txt
  build/static/js/main.14f3b4f0.js.map
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.js
  src/components/auth/UserSignUpForm.js
  src/pages/UserSignUpPage.js
Labels: enhancement

#17 [Auth] 유저 프로필 페이지 추가
  src/App.js
  src/components/auth/UserProfileForm.js
  src/pages/UserProfilePage.js
Labels: enhancement

#24 [Lending] axios인스턴스 생성 & API 함수 작성
  src/lib/api/lending.js
Labels: enhancement

#34 Develop merge
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.js
  src/components/auth/UserProfileForm.js
  src/components/auth/UserSignUpForm.js
  src/index.js
  src/lib/api/auth.js
  src/lib/api/boardInformation.js
  src/lib/api/boardMap.js
  src/lib/api/boardNotice.js
  src/lib/api/client.js
  src/lib/api/composite.js
  src/lib/api/lending.js
  src/lib/api/libraries.js
  src/pages/UserProfilePage.js
  src/pages/UserSignUpPage.js
Labels: enhancement

#46 [Composite] axios 생성 및 api 함수 작성
  src/lib/api/client.js
  src/lib/api/composite.js
Labels: enhancement

#48 [Lending] api 함수 작성
  src/lib/api/lending.js
Labels: enhancement

#40 [Auth] axios인스턴스생성 & API 함수 작성
  package-lock.json
  package.json
  src/lib/api/auth.js
  src/lib/api/client.js
Labels: enhancement

#49 [Board/Information] API 함수 작성
  src/lib/api/boardInformaition.js
Labels: enhancement

#50 [Libraries]API 함수 작성
  src/lib/api/libraries.js
Labels: enhancement

#51 boardNotice.js API 함수 작성
  src/lib/api/boardNotice.js
Labels: enhancement

#52 boardMap.js API 함수 작성
  src/lib/api/boardMap.js
Labels: enhancement

#54 [Auth] 유저 로그인&회원가입 폼 구성하기
  src/components/auth/UserLoginForm.js
  src/components/auth/UserSignUpForm.js
  src/lib/api/auth.js
  src/pages/UserLoginPage.js
Labels: enhancement

#59 [Auth] 로그인 폼 레이아웃 구성 & 통합 페이지 추가
  package-lock.json
  package.json
  src/App.js
  src/components/auth/UserLoginForm.js
  src/index.js
  src/pages/HomePage.js
  src/pages/UserLoginPage.js
  src/styles/components/UserLoginForm.scss
  src/styles/config/_reset.scss
  src/styles/style.scss
Labels: documentation, enhancement

#63 [Auth] 회원가입 폼 구현
  package-lock.json
  package.json
  src/components/auth/UserLoginForm.js
  src/components/auth/UserSignUpForm.js
  src/container/auth/LoginForm.js
  src/container/auth/SignUpForm.js
  src/index.js
  src/lib/api/auth.js
  src/lib/createRequestSaga.js
  src/modules/auth.js
  src/modules/index.js
  src/modules/loading.js
  src/pages/UserLoginPage.js
  src/pages/UserSignUpPage.js
  src/styles/components/UserSignUpForm.scss
  src/styles/style.scss
Labels: documentation, enhancement

#64 [Auth] 회원가입 폼 구현
  package-lock.json
  package.json
  src/components/auth/UserLoginForm.js
  src/components/auth/UserSignUpForm.js
  src/container/auth/LoginForm.js
  src/container/auth/SignUpForm.js
  src/index.js
  src/lib/api/auth.js
  src/lib/createRequestSaga.js
  src/modules/auth.js
  src/modules/index.js
  src/modules/loading.js
  src/pages/UserLoginPage.js
  src/pages/UserSignUpPage.js
  src/styles/components/UserSignUpForm.scss
  src/styles/style.scss
Labels: documentation, enhancement

#65 [Auth] 로그인 기능 오류 수정
  src/components/auth/UserSignUpForm.js
  src/container/auth/LoginForm.js
  src/containers/auth/LoginForm.js
  src/containers/auth/SignUpForm.js
  src/lib/api/auth.js
  src/modules/index.js
  src/modules/user.js
  src/pages/UserLoginPage.js
  src/pages/UserSignUpPage.js
Labels: enhancement

#66 [Auth] 로그인 기능 구현 및 오류 수정
  src/components/auth/UserSignUpForm.js
  src/container/auth/LoginForm.js
  src/containers/auth/LoginForm.js
  src/containers/auth/SignUpForm.js
  src/lib/api/auth.js
  src/modules/index.js
  src/modules/user.js
  src/pages/UserLoginPage.js
  src/pages/UserSignUpPage.js
Labels: documentation, enhancement

#67 [LibrariesList] 폼 구성 및 간단한 css착업
  src/App.js
  src/components/libraries/LibrariesList.js
  src/components/libraries/LibrariesListItem.js
  src/pages/LibrariesListPage.js
  src/styles/components/libraries/LibrariesList.scss
  src/styles/components/libraries/LibrariesListItem.scss
  src/styles/style.scss
Labels: documentation, enhancement

#68 BoardList 추가
  src/App.js
  src/components/libraries/LibrariesList.js
  src/components/libraries/LibrariesListItem.js
  src/pages/LibrariesListPage.js
  src/styles/components/libraries/LibrariesList.scss
  src/styles/components/libraries/LibrariesListItem.scss
  src/styles/style.scss
Labels: documentation, enhancement

#72 [LibrariesList] axios.get 오류 수정
  src/components/libraries/LibrariesList.js
  src/components/libraries/LibrariesListItem.js
  src/styles/components/libraries/LibrariesList.scss
  src/styles/components/libraries/LibrariesListItem.scss
Labels: documentation, enhancement

#73 Feature/auth/user profile
  src/components/auth/UserProfileForm.js
  src/containers/auth/LoginForm.js
  src/containers/auth/ProfileForm.js
  src/containers/auth/SignUpForm.js
  src/lib/api/auth.js
  src/modules/auth.js
  src/pages/UserProfilePage.js
  src/styles/components/UserLoginForm.scss
  src/styles/components/UserPropfileForm.scss
  src/styles/components/UserSignUpForm.scss
  src/styles/style.scss
Labels: documentation, enhancement

#74 도서관 찾기 시 리스트 출력 오류 수정 및 회원정보 출력 확인
  src/components/auth/UserProfileForm.js
  src/components/libraries/LibrariesList.js
  src/components/libraries/LibrariesListItem.js
  src/containers/auth/LoginForm.js
  src/containers/auth/ProfileForm.js
  src/containers/auth/SignUpForm.js
  src/lib/api/auth.js
  src/modules/auth.js
  src/pages/UserProfilePage.js
  src/styles/components/UserLoginForm.scss
  src/styles/components/UserPropfileForm.scss
  src/styles/components/UserSignUpForm.scss
  src/styles/components/libraries/LibrariesList.scss
  src/styles/components/libraries/LibrariesListItem.scss
  src/styles/style.scss
Labels: documentation, enhancement

#82 프로필 페이지 보류 및 로그인 선택페이지 추가
  package.json
  src/App.js
  src/components/auth/UserProfileForm.js
  src/containers/auth/ProfileForm.js
  src/modules/auth.js
  src/pages/HomePage.js
  src/pages/LoginSelectorPage.js
  src/styles/components/UserPropfileForm.scss
Labels: enhancement, wontfix

#85 [Board] 통합 게시판 페이지 생성 & reset.scss수정
  package-lock.json
  package.json
  src/components/board/GuideForm.js
  src/components/board/NoticesList.js
  src/components/board/NoticesListItem.js
  src/pages/GuidePage.js
  src/pages/NoticesPage.js
  src/styles/components/board/GuideForm.scss
  src/styles/components/board/NoticesList.scss
  src/styles/components/board/NoticesListItem.scss
  src/styles/config/_reset.scss
  src/styles/style.scss
Labels: enhancement, good first issue

#88 [Board] 개별도서관 게시판 페이지 추가
  src/App.js
  src/components/board/BoardDetail.js
  src/components/board/BoardDetailForm.js
  src/components/board/BoardInfo.js
  src/components/board/BoardList.js
  src/components/board/BoardMap.js
  src/components/board/BoardNoticeListItem.js
  src/components/board/BoardSideBar.js
  src/pages/board/BoardDetailPage.js
  src/pages/board/BoardListPage.js
  src/pages/board/GuidePage.js
  src/pages/board/NoticesPage.js
  src/styles/components/board/BoardDetail.scss
  src/styles/components/board/BoardDetailForm.scss
  src/styles/components/board/BoardInfo.scss
  src/styles/components/board/BoardList.scss
  src/styles/components/board/BoardListItem.scss
  src/styles/components/board/BoardSideBar.scss
  src/styles/style.scss
Labels: enhancement, good first issue

#89 composite 페이지 추가
  src/App.js
  src/pages/HomePage.js
  src/pages/composite/CompositeDeatailPage.js
  src/pages/composite/CompositeListPage.js
Labels: enhancement, good first issue

#91 lending & reservation page 추가
  src/App.js
  src/pages/UserMainPage.js
  src/pages/lending/LendingRecordPage.js
  src/pages/lending/ReservationListPage.js
Labels: enhancement

#94 [Board] route연결 및 도서관 개별 페이지 추가
  src/App.js
  src/components/board/BoardList.js
  src/components/board/BoardNoticeListItem.js
  src/components/board/NoticesDetail.js
  src/components/board/NoticesList.js
  src/components/board/NoticesListItem.js
  src/components/libraries/LibrariesList.js
  src/components/libraries/LibrariesListItem.js
  src/pages/HomePage.js
  src/pages/LibraryMainPage.js
  src/pages/board/NoticesDetailPage.js
  src/pages/libraries/LibrariesListPage.js
  src/styles/components/LibraryMainPage.scss
  src/styles/components/board/NoticeDetail.scss
  src/styles/components/board/NoticesList.scss
  src/styles/components/board/NoticesListItem.scss
  src/styles/style.scss
Labels: documentation, enhancement

#93 [Auth] 마이페이지 UI 오류 수정
  src/components/auth/UserProfileForm.js
  src/containers/auth/ProfileForm.js
Labels: enhancement

#95 Feature/auth/update/user main page
  .gitignore
  public/img/alabaster-co-DC98wz4vNws-unsplash.jpg
  src/components/UserMainForm.js
  src/components/auth/UserProfileForm.js
  src/containers/UserMain.js
  src/pages/UserMainPage.js
  src/styles/UserMainForm.scss
  src/styles/components/auth/UserLoginForm.scss
  src/styles/components/auth/UserPropfileForm.scss
  src/styles/components/auth/UserSignUpForm.scss
  src/styles/style.scss
Labels: documentation, enhancement

#96 Revert "Feature/auth/update/user main page"
  .gitignore
  public/img/alabaster-co-DC98wz4vNws-unsplash.jpg
  src/components/UserMainForm.js
  src/components/auth/UserProfileForm.js
  src/containers/UserMain.js
  src/pages/UserMainPage.js
  src/styles/UserMainForm.scss
  src/styles/components/UserLoginForm.scss
  src/styles/components/UserPropfileForm.scss
  src/styles/components/UserSignUpForm.scss
  src/styles/style.scss
Labels: documentation, enhancement

#97 Revert "Revert "Feature/auth/update/user main page""
  .gitignore
  public/img/alabaster-co-DC98wz4vNws-unsplash.jpg
  src/components/UserMainForm.js
  src/components/auth/UserProfileForm.js
  src/containers/UserMain.js
  src/pages/UserMainPage.js
  src/styles/UserMainForm.scss
  src/styles/components/auth/UserLoginForm.scss
  src/styles/components/auth/UserPropfileForm.scss
  src/styles/components/auth/UserSignUpForm.scss
  src/styles/style.scss
Labels: documentation, enhancement

#98 [Auth] 아이디&비밀번호 찾기 페이지 추가
  src/App.js
  src/components/auth/FindIdForm.js
  src/components/auth/FindPwForm.js
  src/containers/auth/FindId.js
  src/containers/auth/FindPw.js
  src/pages/auth/FindIdPage.js
  src/pages/auth/FindPasswordPage.js
  src/pages/auth/FindPwPage.js
  src/styles/UserMainForm.scss
  src/styles/components/auth/FindIdForm.scss
  src/styles/components/auth/FindPwForm.scss
  src/styles/style.scss
Labels: duplicate, enhancement

#104 [Auth] 홈페이지 도서 검색 UI 추가
  src/components/UserMainForm.js
  src/pages/HomePage.js
  src/styles/home/homepage.scss
  src/styles/home/searchBar.scss
  src/styles/homepage.scss
  src/styles/style.scss
Labels: documentation, enhancement

#109 [libraries] 개별 도서관 페이지 및 상세정보 페이지
  src/App.js
  src/components/board/BoardList.js
  src/components/board/BoardNoticeListItem.js
  src/components/libraries/LibrariesDetail.js
  src/components/libraries/LibraryMainForm.js
  src/pages/libraries/LibrariesDetailPage.js
  src/styles/components/libraries/LibrariesDetail.scss
  src/styles/components/libraries/LibraryMainForm.scss
  src/styles/style.scss
Labels: documentation, enhancement

#111 [Boards] axios연결
  src/components/board/BoardDetail.js
  src/components/board/BoardDetailForm.js
  src/components/board/BoardInfo.js
  src/components/board/BoardList.js
  src/components/board/BoardNoticeListItem.js
  src/components/board/GuideForm.js
  src/components/board/NoticesDetail.js
  src/components/board/NoticesList.js
  src/components/board/NoticesListItem.js
  src/pages/board/BoardDetailPage.js
  src/styles/components/board/BoardDetail.scss
  src/styles/style.scss
Labels: enhancement

#113 Feature/auth/hompage UI slide
  public/img/clay-banks-w_qTfiPbjbg-unsplash.jpg
  public/img/janko-ferlic-sfL_QOnmy00-unsplash.jpg
  public/img/negipho-u59gG_FIGIo-unsplash.jpg
  public/img/pero-kalimero-9BJRGlqoIUk-unsplash.jpg
  src/pages/HomePage.js
  src/pages/home/FeatureDescriptions.js
  src/pages/home/Footer.js
  src/pages/home/Header.js
  src/pages/home/Quote.js
  src/pages/home/SearchBar.js
  src/pages/useCount.js
  src/styles/home/feature/counts.scss
  src/styles/home/feature/feature.scss
  src/styles/home/feature/reading.scss
  src/styles/home/feature/register.scss
  src/styles/home/feature/reservation.scss
  src/styles/home/footer.scss
  src/styles/home/header.scss
  src/styles/home/homepage.scss
  src/styles/home/navigations.scss
  src/styles/home/quote.scss
  src/styles/home/searchBar.scss
  src/styles/style.scss
Labels: documentation, enhancement

#116 [Libraries] css 수정
  src/components/libraries/LibrariesListItem.js
  src/styles/components/libraries/LibrariesDetail.scss
  src/styles/components/libraries/LibrariesList.scss
  src/styles/components/libraries/LibrariesListItem.scss
  src/styles/components/libraries/LibraryMainForm.scss
Labels: documentation

#118 [Boards] filter적용 및 css 수정
  src/App.js
  src/components/board/BoardDetailForm.js
  src/components/board/BoardInfo.js
  src/components/board/BoardList.js
  src/components/board/GuideForm.js
  src/components/board/NoticesDetail.js
  src/components/board/NoticesList.js
  src/styles/components/board/BoardDetailForm.scss
  src/styles/components/board/BoardInfo.scss
  src/styles/components/board/BoardList.scss
  src/styles/components/board/BoardListItem.scss
  src/styles/components/board/BoardSideBar.scss
  src/styles/components/board/GuideForm.scss
  src/styles/components/board/NoticeDetail.scss
  src/styles/components/board/NoticesList.scss
  src/styles/components/board/NoticesListItem.scss
Labels: documentation, enhancement

#117 Feature/search book list
  src/App.js
  src/components/composite/CategoryFilter.js
  src/components/composite/CompositeDetail.js
  src/components/composite/CompositeListForm.js
  src/components/composite/CompositeListItem.js
  src/components/composite/LibraryFilter.js
  src/components/composite/SearchFilter.js
  src/containers/UserMain.js
  src/pages/composite/CompositeDeatailPage.js
  src/pages/composite/CompositeListPage.js
Labels: enhancement

#119 로그인 선택 페이지 이미지 로딩속도 수정
  src/components/auth/LoginSeletorForm.js
  src/containers/auth/LoginSelector.js
  src/styles/components/auth/LoginSelector.scss
  src/styles/home/feature/reading.scss
  src/styles/style.scss
Labels: documentation

#121 통합 홈페이지 UI 오류 수정
  src/pages/HomePage.js
  src/pages/home/FeatureDescriptions.js
  src/pages/home/Quote.js
  src/styles/home/header.scss
Labels: enhancement

#125 [libraries] icon 추가 및 css 수정
  src/components/libraries/LibrariesDetail.js
  src/styles/components/libraries/LibrariesDetail.scss
Labels: documentation

#123 Feature/auth/fix login UI
  src/components/auth/UserLoginForm.js
  src/pages/HomePage.js
  src/styles/components/auth/UserLoginForm.scss
  src/styles/components/auth/inputForm.scss
  src/styles/home/header.scss
  src/styles/style.scss
Labels: documentation, enhancement

#129 회원가입 페이지 디자인 변경
  src/components/auth/UserSignUpForm.js
  src/pages/home/FeatureDescriptions.js
  src/styles/components/auth/UserLoginForm.scss
  src/styles/components/auth/UserSignUpForm.scss
  src/styles/style.scss
Labels: documentation

#131 server api 수정
  src/components/board/BoardDetailForm.js
  src/components/board/BoardList.js
  src/components/board/GuideForm.js
  src/components/board/NoticesDetail.js
  src/components/board/NoticesList.js
  src/components/composite/CompositeDetail.js
  src/components/composite/CompositeListForm.js
  src/components/libraries/LibrariesDetail.js
  src/components/libraries/LibrariesList.js
  src/containers/auth/LoginSelector.js
Labels: enhancement

#136 [Boards] 이용안내 페이지 데이터 없으면 흰 화면만 뜨는 오류 해결
  src/components/board/BoardInfo.js
  src/components/board/BoardList.js
  src/components/board/GuideForm.js
Labels: enhancement

#137 [Board]오류 해결 및 오시는 길, libraries css 작업
  src/components/board/BoardInfo.js
  src/components/board/BoardList.js
  src/components/board/BoardMap.js
  src/components/board/NoticesList.js
  src/components/libraries/LibraryMainForm.js
  src/styles/components/board/BoardMap.scss
  src/styles/components/board/NoticeDetail.scss
  src/styles/components/libraries/LibrariesDetail.scss
  src/styles/components/libraries/LibrariesListItem.scss
  src/styles/components/libraries/LibraryMainForm.scss
Labels: enhancement

#140 로그인 & 로그아웃 기능 추가
  package.json
  src/components/UserMainForm.js
  src/components/auth/UserLoginForm.js
  src/containers/UserMain.js
  src/containers/auth/LoginForm.js
  src/lib/api/auth.js
  src/lib/createRequestSaga.js
  src/modules/auth.js
  src/styles/UserMainForm.scss
  src/styles/components/auth/UserLoginForm.scss
Labels: documentation, enhancement

#142 프로필 정보 보여주기
  src/components/auth/UserProfileForm.js
  src/containers/auth/SignUpForm.js
  src/lib/api/auth.js
  src/pages/UserMainPage.js
  src/pages/auth/FindIdPage.js
  src/pages/auth/FindPwPage.js
  src/pages/auth/UserLoginPage.js
  src/pages/auth/UserProfilePage.js
  src/pages/auth/UserSignUpPage.js
Labels: enhancement
