Repository 247CloudLibrary/client-users, pull requests merged in 2022-05, with the labels that each got.

#144 전체적인 css 수정
  src/components/libraries/LibrariesSearchFilter.js
  src/styles/components/board/BoardDetailForm.scss
  src/styles/components/board/BoardList.scss
  src/styles/components/board/GuideForm.scss
  src/styles/components/board/NoticeDetail.scss
  src/styles/components/board/NoticesList.scss
  src/styles/components/libraries/LibrariesDetail.scss
  src/styles/components/libraries/LibrariesList.scss
  src/styles/components/libraries/LibrariesListItem.scss
  src/styles/components/libraries/LibraryMainForm.scss
Labels: documentation

#146 Feature/auth/find
  src/components/auth/FindIdForm.js
  src/containers/auth/FindId.js
Labels: enhancement

#149 compositeList css 수정
  src/components/composite/CompositeListItem.js
  src/styles/components/composite/CompositeListForm.scss
  src/styles/components/composite/CompositeListItem.scss
  src/styles/components/libraries/LibrariesList.scss
Labels: documentation

#153 아이디 찾기 비밀번호 찾기 CSS
  src/components/auth/FindIdForm.js
  src/components/auth/FindPwForm.js
  src/containers/auth/FindId.js
  src/styles/components/auth/FindIdForm.scss
  src/styles/components/auth/FindPwForm.scss
Labels: documentation, enhancement

#155 Header 추가 / composite lending css 수정
  src/components/common/Header.js
  src/components/composite/CompositeDetail.js
  src/components/lending/LendingListForm.js
  src/pages/composite/CompositeDeatailPage.js
  src/pages/composite/CompositeListPage.js
  src/pages/lending/LendingRecordPage.js
  src/styles/common/header.scss
  src/styles/components/composite/CompositeDetail.scss
  src/styles/components/composite/CompositeListForm.scss
  src/styles/components/lending/LendingListForm.scss
  src/styles/style.scss
Labels: documentation

#156 header 추가 및 axios url 변경
  src/components/board/BoardDetailForm.js
  src/components/board/BoardList.js
  src/components/board/BoardNoticeListItem.js
  src/components/board/BoardSideBar.js
  src/components/board/GuideForm.js
  src/components/board/NoticesDetail.js
  src/components/board/NoticesList.js
  src/components/libraries/LibrariesDetail.js
  src/components/libraries/LibrariesList.js
  src/components/libraries/LibraryMainForm.js
  src/styles/components/board/BoardDetailForm.scss
  src/styles/components/board/BoardList.scss
  src/styles/components/board/GuideForm.scss
  src/styles/components/board/NoticeDetail.scss
  src/styles/components/board/NoticesList.scss
  src/styles/components/libraries/LibrariesDetail.scss
  src/styles/components/libraries/LibrariesList.scss
  src/styles/components/libraries/LibrariesListItem.scss
  src/styles/components/libraries/LibraryMainForm.scss
Labels: documentation, enhancement

#157 비밀번호 변경 구현
  src/App.js
  src/components/UserMainForm.js
  src/components/auth/ChangePasswordForm.js
  src/components/auth/UserProfileForm.js
  src/components/auth/UserSignUpForm.js
  src/containers/UserMain.js
  src/pages/auth/ChangePasswordPage.js
  src/styles/UserMainForm.scss
  src/styles/components/auth/ChangePassword.scss
  src/styles/components/auth/UserPropfileForm.scss
  src/styles/style.scss
Labels: documentation, enhancement

#160 예약 기능 구현 완료
  src/components/composite/CompositeDetail.js
  src/components/composite/CompositeListItem.js
  src/components/lending/ReservationListForm.js
  src/components/lending/ReservationListItem.js
  src/pages/lending/ReservationListPage.js
  src/styles/components/composite/CompositeDetail.scss
  src/styles/components/composite/CompositeListItem.scss
  src/styles/components/lending/ReservationListForm.scss
  src/styles/components/lending/ReservationListItem.scss
  src/styles/style.scss
Labels: enhancement
